services:
  backend:
    build:
      dockerfile: docker_files/backend.dockerfile
    command: python main.py
    container_name: backend
    working_dir: /sudoku_solver
    ports:
      - 5000:5000
    volumes:
      - ./core:/sudoku_solver/core
      - ./main.py:/sudoku_solver/main.py
    networks:
      - sudoku

  frontend:
    build:
      dockerfile: docker_files/frontend.dockerfile
    container_name: frontend
    working_dir: /sudoku_solver/app
    ports:
      - 8080:8080
    networks:
      - sudoku
#    volumes:
#      - ./app/app:/sudoku_solver/app

networks:
  sudoku:
    driver: bridge
